name: Lighthouse

on: [pull_request]

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v3

      - name: Use Node.js 16.x (LTS)
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci

      - name: Use Ruby 2.7.3
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'
          bundler-cache: true
          working-directory: docs

      - name: Build docs
        run: npm run build:docs
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Lighthouse CI
        run: npx @lhci/cli@0.9.x autorun
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LHCI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
