name: Build

on:
  pull_request:
  push:

jobs:
  test-node:
    name: Test on Node.js
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the project
      uses: actions/checkout@v3
    - name: Use Node.js 16.x (LTS)
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - name: Lint Codebase
      run: npm run lint
    - name: Run Node.js Tests
      run: npm run test
    - name: Check Bundle Size
      run: npm run size
